COMMAND_DOCS = {
    "home": {
        "description": "Move the robot to its home position.",
        "usage": "home",
        "examples": ["home", "move_home"],
        "notes": "No arguments.",
    },
    "park": {
        "description": "Move the robot to a safe parked position.",
        "usage": "park",
        "examples": ["park"],
        "notes": "No arguments.",
    },
    "base": {
        "description": "Set the absolute base joint angle in radians.",
        "usage": "base <angle>",
        "examples": ["base 0.0", "base 1.57"],
        "range": {"angle": [-3.14159, 3.14159]},
    },
    "arm": {
        "description": "Set the absolute arm joint angle in radians.",
        "usage": "arm <angle>",
        "examples": ["arm 0.0", "arm -1.2"],
        "range": {"angle": [-1.50, 1.50]},
    },
    "shaft": {
        "description": "Set the shaft position.",
        "usage": "shaft <position>",
        "examples": ["shaft -0.10"],
        "range": {"position": [-0.15, 0.0]},
    },
    "base_rel": {
        "description": "Move the base joint relative to the current angle.",
        "usage": "base_rel <delta>",
        "examples": ["base_rel 0.2"],
        "range": {"delta": [-1.57, 1.57]},
    },
    "arm_rel": {
        "description": "Move the arm joint relative to the current angle.",
        "usage": "arm_rel <delta>",
        "examples": ["arm_rel -0.2"],
        "range": {"delta": [-1.50, 1.50]},
    },
    "shaft_rel": {
        "description": "Move the shaft relative to the current position.",
        "usage": "shaft_rel <delta>",
        "examples": ["shaft_rel 0.05"],
        "range": {"delta": [-0.15, 0.15]},
    },
    "move_to": {
        "description": "Move the end effector to an XYZ target.",
        "usage": "move_to <x> <y> <z>",
        "examples": ["move_to 0.20 0.10 -0.05"],
        "range": {"x": [-0.60, 0.60], "y": [-0.60, 0.60], "z": [-0.15, 0.0]},
        "notes": "Target must be reachable by the SCARA arm.",
    },
    "where": {
        "description": "Report the current robot pose.",
        "usage": "where",
        "examples": ["where"],
        "notes": "No arguments.",
    },
    "grip": {
        "description": "Open the gripper.",
        "usage": "grip",
        "examples": ["grip", "open_gripper"],
        "notes": "No arguments.",
    },
    "release": {
        "description": "Close the gripper.",
        "usage": "release",
        "examples": ["release", "close_gripper"],
        "notes": "No arguments.",
    },
    "pick": {
        "description": "Execute a pick action.",
        "usage": "pick",
        "examples": ["pick"],
        "notes": "No arguments.",
    },
    "place": {
        "description": "Execute a place action.",
        "usage": "place",
        "examples": ["place"],
        "notes": "No arguments.",
    },
    "save_pos": {
        "description": "Save the current position under a name.",
        "usage": "save_pos <name>",
        "examples": ["save_pos bin1"],
    },
    "goto_pos": {
        "description": "Move to a previously saved position.",
        "usage": "goto_pos <name>",
        "examples": ["goto_pos bin1"],
    },
    "list_pos": {
        "description": "List saved positions.",
        "usage": "list_pos",
        "examples": ["list_pos"],
        "notes": "No arguments.",
    },
    "delete_pos": {
        "description": "Delete a saved position by name.",
        "usage": "delete_pos <name>",
        "examples": ["delete_pos bin1"],
    },
    "speed": {
        "description": "Set the speed factor.",
        "usage": "speed <factor>",
        "examples": ["speed 1.0", "speed 0.5"],
        "range": {"factor": [0.1, 2.0]},
    },
    "led": {
        "description": "Set LED state.",
        "usage": "led <on|off>",
        "examples": ["led on", "led off"],
    },
    "wait": {
        "description": "Pause execution for a number of seconds.",
        "usage": "wait <seconds>",
        "examples": ["wait 1.5"],
        "range": {"seconds": [0.0, 3600.0]},
    },
    "status": {
        "description": "Report controller status.",
        "usage": "status",
        "examples": ["status"],
        "notes": "No arguments.",
    },
    "verbose": {
        "description": "Set verbosity level.",
        "usage": "verbose <level>",
        "examples": ["verbose 0", "verbose 2"],
        "range": {"level": [0, 2]},
    },
    "clear": {
        "description": "Clear state or reset transient output.",
        "usage": "clear",
        "examples": ["clear"],
        "notes": "No arguments.",
    },
    "quit": {
        "description": "Exit the controller.",
        "usage": "quit",
        "examples": ["quit"],
        "notes": "No arguments.",
    },
    "exit": {
        "description": "Exit the controller.",
        "usage": "exit",
        "examples": ["exit"],
        "notes": "No arguments.",
    },
}