# Generated by Django 6.0.5 on 2026-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
