# Generated by Django 6.0.5 on 2026-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_user_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='./storage/default/default.png', upload_to='./storage'),
        ),
    ]
