# Generated by Django 6.0.5 on 2026-08-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='change this', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='user', max_length=64),
        ),
    ]
